name: build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: '9.x'
  SLN_FILE: 'RL UPKSuite-linux.Filter.slnf'

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore ${{env.SLN_FILE}}
      
    - name: Build
      run: dotnet build --no-restore ${{env.SLN_FILE}}

    - name: Test with the dotnet CLI
      run: dotnet test --no-build ${{env.SLN_FILE}}
